# labels.py

PROCESSED_LABELS = [
    '([potholes])',
    '(<downed> [bollard])',
    '(<down> [power line]) in ([street]/[bike lane]/[side walk])',
    '([flooding]/[sewage backup]) in ([bike lane])',
    '(<unclear>/<faded> [bike lane painting/striping])',
    '(<broken> [street signs])',
    '(<broken> [traffic lights])',
    '([car]) blocking ([bike lane])',
    '([car]) blocking ([fire hydrant])',
    '([car]) blocking ([red curb])',
    '([dumped vegetation])',
    '([dumped trash])',
    '([shattered glass]/[debris])',
    '([yard waste piles])',
    '([residential trash cans]) in ([bike lane])',
    '([commercial dumpsters]) in ([bike lane])',
    '([graffiti])',
    '([construction signs])',
    '([orange construction cones])',
    '(<blocked> [roads])',
    '([streetlight] <outage>)',
    '([tree overhang])',
    '(<burned> [car])',
    '([car]) on ([jacks]/[blocks])',
    '([car]) with (<missing>/<shattered> [car windows])',
    '([car]) with (<missing> [car wheels])',
    '([mobile retailers]) setting up in ([bike lanes])',
    '([person])',
    '([car])',
]
