# labels.py

PROCESSED_LABELS = [
    '([Potholes])',
    '(<Downed> [bollard])',
    '(<Down> [power line]) in ([street]/[bike lane]/[side walk])',
    '([Flooding]/[sewage backup]) in ([bike lane])',
    '(<Unclear>/<faded> [bike lane painting/striping])',
    '(<Broken> [street signs])',
    '(<Broken> [traffic lights])',
    '([Vehicle]) blocking ([bike lane])',
    '([Vehicle]) blocking ([fire hydrant])',
    '([Vehicle]) blocking ([red curb])',
    '([Dumped vegetation])',
    '([Dumped trash])',
    '([Glass]/[debris])',
    '([Yard waste piles])',
    '([Residential trash cans]) in ([bike lane])',
    '([Commercial dumpsters]) in ([bike lane])',
    '([Graffiti])',
    '([Construction signs])',
    '([Orange construction cones])',
    '(<Blocked> [roads])',
    '([Streetlight] <outage>)',
    '([Tree overhang])',
    '(<Burned> [vehicles])',
    '([Vehicles]) on ([jacks]/[blocks])',
    '([Vehicles]) with (<missing>/<shattered> [windows])',
    '([Vehicles]) with (<missing> [tires]/[wheels])',
    '([Mobile retailers]) setting up in ([bike lanes])',
    '([Person])',
    '([Vehicle])',
]
