import sameple_img from "./sidewalk.png";

const sampleTasks = [
  {
    id: 1,
    image: sameple_img,
    title: "Broken Street Light",
    confidence: 91,
    status: "verified",
    assignedTo: "",
    verifiedBy: "auto",
    location: "5th Ave & Main St",
    timestamp: "2025-06-21 08:30:00",
  },
  {
    id: 2,
    image: sameple_img,
    title: "Flooded Bike Lane",
    confidence: 68,
    status: "unverified",
    assignedTo: "",
    verifiedBy: "",
    location: "7th St & Maple",
    timestamp: "2025-06-21 10:10:00",
  },
  {
    id: 3,
    image: sameple_img,
    title: "Pothole on Road",
    confidence: 94,
    status: "assigned",
    assignedTo: "John Doe",
    verifiedBy: "staff",
    location: "Elm St & Pine",
    timestamp: "2025-06-20 17:55:00",
  },
  {
    id: 4,
    image: sameple_img,
    title: "Fallen Tree Branch",
    confidence: 75,
    status: "unverified",
    assignedTo: "",
    verifiedBy: "",
    location: "Oak St & 3rd Ave",
    timestamp: "2025-06-20 16:45:00",
  },
  {
    id: 5,
    image: sameple_img,
    title: "Graffiti on Wall",
    confidence: 85,
    status: "verified",
    assignedTo: "",
    verifiedBy: "staff",
    location: "Main St & 10th Ave",
    timestamp: "2025-06-20 15:30:00",
  },
  {
    id: 6,
    image: sameple_img,
    title: "Blocked Sidewalk",
    confidence: 89,
    status: "assigned",
    assignedTo: "Alice Smith",
    verifiedBy: "auto",
    location: "Maple Rd & 2nd",
    timestamp: "2025-06-20 14:00:00",
  },
  {
    id: 7,
    image: sameple_img,
    title: "Water Leak",
    confidence: 62,
    status: "unverified",
    assignedTo: "",
    verifiedBy: "",
    location: "Spruce & Market",
    timestamp: "2025-06-20 13:15:00",
  },
  {
    id: 8,
    image: sameple_img,
    title: "Faded Crosswalk Paint",
    confidence: 77,
    status: "verified",
    assignedTo: "",
    verifiedBy: "staff",
    location: "8th St & Jackson",
    timestamp: "2025-06-20 12:30:00",
  },
  {
    id: 9,
    image: sameple_img,
    title: "Overflowing Trash Can",
    confidence: 80,
    status: "finished",
    assignedTo: "Robert Lee",
    verifiedBy: "auto",
    location: "12th & Lincoln",
    timestamp: "2025-06-20 11:00:00",
  },
  {
    id: 10,
    image: sameple_img,
    title: "Damaged Traffic Sign",
    confidence: 90,
    status: "assigned",
    assignedTo: "Sarah Kim",
    verifiedBy: "staff",
    location: "Park Ave & 6th",
    timestamp: "2025-06-20 09:30:00",
  },
];

export default sampleTasks;
